# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windows.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1129, 744)
        MainWindow.setMinimumSize(QtCore.QSize(498, 450))
        MainWindow.setMaximumSize(QtCore.QSize(3000, 900))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/simple/.designer/backup/images/line.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(244, 10, 54, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(694, 10, 54, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(244, 70, 54, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(694, 70, 54, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(284, 20, 381, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(244, 60, 421, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(233, 28, 20, 41))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(654, 27, 20, 41))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(1103, 27, 30, 41))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(683, 28, 20, 41))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(734, 20, 381, 16))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(694, 60, 421, 20))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(1109, 87, 20, 41))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setGeometry(QtCore.QRect(683, 88, 20, 41))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(734, 80, 381, 16))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setGeometry(QtCore.QRect(694, 120, 421, 20))
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.line_17 = QtWidgets.QFrame(self.centralwidget)
        self.line_17.setGeometry(QtCore.QRect(654, 87, 20, 41))
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.line_18 = QtWidgets.QFrame(self.centralwidget)
        self.line_18.setGeometry(QtCore.QRect(233, 88, 20, 41))
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.line_19 = QtWidgets.QFrame(self.centralwidget)
        self.line_19.setGeometry(QtCore.QRect(284, 80, 381, 16))
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.line_20 = QtWidgets.QFrame(self.centralwidget)
        self.line_20.setGeometry(QtCore.QRect(244, 120, 421, 20))
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(245, 100, 411, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.add_goods_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.add_goods_lineEdit.setObjectName("add_goods_lineEdit")
        self.horizontalLayout.addWidget(self.add_goods_lineEdit)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.add_goods_time = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.add_goods_time.setProperty("value", 5.0)
        self.add_goods_time.setObjectName("add_goods_time")
        self.horizontalLayout.addWidget(self.add_goods_time)
        self.add_goods_button = QtWidgets.QPushButton(self.layoutWidget)
        self.add_goods_button.setObjectName("add_goods_button")
        self.horizontalLayout.addWidget(self.add_goods_button)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(245, 40, 414, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.keep_T = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.keep_T.setMaximum(150.0)
        self.keep_T.setProperty("value", 30.0)
        self.keep_T.setObjectName("keep_T")
        self.horizontalLayout_2.addWidget(self.keep_T)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.keep_T_time = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.keep_T_time.setMaximum(120.0)
        self.keep_T_time.setObjectName("keep_T_time")
        self.horizontalLayout_2.addWidget(self.keep_T_time)
        self.keep_T_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.keep_T_button.setObjectName("keep_T_button")
        self.horizontalLayout_2.addWidget(self.keep_T_button)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(695, 40, 422, 25))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.change_T = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.change_T.setMaximum(150.0)
        self.change_T.setObjectName("change_T")
        self.horizontalLayout_3.addWidget(self.change_T)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.change_T_rate = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.change_T_rate.setMaximum(5.0)
        self.change_T_rate.setObjectName("change_T_rate")
        self.horizontalLayout_3.addWidget(self.change_T_rate)
        self.change_T_button = QtWidgets.QPushButton(self.layoutWidget2)
        self.change_T_button.setObjectName("change_T_button")
        self.horizontalLayout_3.addWidget(self.change_T_button)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(695, 100, 422, 25))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.blow_off_water_T = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        self.blow_off_water_T.setProperty("value", 60.0)
        self.blow_off_water_T.setObjectName("blow_off_water_T")
        self.horizontalLayout_4.addWidget(self.blow_off_water_T)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.blow_off_water_rate = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        self.blow_off_water_rate.setMaximum(10.0)
        self.blow_off_water_rate.setProperty("value", 3.0)
        self.blow_off_water_rate.setObjectName("blow_off_water_rate")
        self.horizontalLayout_4.addWidget(self.blow_off_water_rate)
        self.blow_off_water_button = QtWidgets.QPushButton(self.layoutWidget3)
        self.blow_off_water_button.setObjectName("blow_off_water_button")
        self.horizontalLayout_4.addWidget(self.blow_off_water_button)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(240, 140, 880, 551))
        self.graphicsView.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.graphicsView.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.graphicsView.setObjectName("graphicsView")
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 10, 221, 308))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.processList = QtWidgets.QListWidget(self.layoutWidget4)
        self.processList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.processList.setAutoScroll(True)
        self.processList.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.processList.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.processList.setObjectName("processList")
        self.gridLayout.addWidget(self.processList, 0, 0, 1, 2)
        self.processUpButton = QtWidgets.QPushButton(self.layoutWidget4)
        self.processUpButton.setObjectName("processUpButton")
        self.gridLayout.addWidget(self.processUpButton, 1, 0, 1, 1)
        self.processDownButton = QtWidgets.QPushButton(self.layoutWidget4)
        self.processDownButton.setObjectName("processDownButton")
        self.gridLayout.addWidget(self.processDownButton, 1, 1, 1, 1)
        self.insertProcessButton = QtWidgets.QPushButton(self.layoutWidget4)
        self.insertProcessButton.setObjectName("insertProcessButton")
        self.gridLayout.addWidget(self.insertProcessButton, 2, 0, 1, 1)
        self.deleteProcessButton = QtWidgets.QPushButton(self.layoutWidget4)
        self.deleteProcessButton.setObjectName("deleteProcessButton")
        self.gridLayout.addWidget(self.deleteProcessButton, 2, 1, 1, 1)
        self.addProcessButton = QtWidgets.QPushButton(self.layoutWidget4)
        self.addProcessButton.setObjectName("addProcessButton")
        self.gridLayout.addWidget(self.addProcessButton, 3, 0, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.layoutWidget5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(12, 331, 221, 361))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 0, 1, 1)
        self.stepTable = QtWidgets.QTableWidget(self.layoutWidget5)
        self.stepTable.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.stepTable.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stepTable.setLineWidth(10)
        self.stepTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.stepTable.setAutoScrollMargin(16)
        self.stepTable.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.stepTable.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.stepTable.setRowCount(0)
        self.stepTable.setColumnCount(4)
        self.stepTable.setObjectName("stepTable")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.stepTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stepTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.stepTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.stepTable.setHorizontalHeaderItem(3, item)
        self.stepTable.horizontalHeader().setVisible(True)
        self.stepTable.horizontalHeader().setCascadingSectionResizes(False)
        self.stepTable.horizontalHeader().setDefaultSectionSize(54)
        self.stepTable.horizontalHeader().setHighlightSections(True)
        self.stepTable.horizontalHeader().setMinimumSectionSize(20)
        self.stepTable.horizontalHeader().setSortIndicatorShown(False)
        self.stepTable.horizontalHeader().setStretchLastSection(False)
        self.stepTable.verticalHeader().setVisible(False)
        self.stepTable.verticalHeader().setCascadingSectionResizes(False)
        self.stepTable.verticalHeader().setDefaultSectionSize(29)
        self.stepTable.verticalHeader().setMinimumSectionSize(24)
        self.stepTable.verticalHeader().setSortIndicatorShown(False)
        self.stepTable.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.stepTable, 1, 0, 1, 2)
        self.stepUpButton = QtWidgets.QPushButton(self.layoutWidget5)
        self.stepUpButton.setObjectName("stepUpButton")
        self.gridLayout_2.addWidget(self.stepUpButton, 2, 0, 1, 1)
        self.stepDownButton = QtWidgets.QPushButton(self.layoutWidget5)
        self.stepDownButton.setObjectName("stepDownButton")
        self.gridLayout_2.addWidget(self.stepDownButton, 2, 1, 1, 1)
        self.editStepButton = QtWidgets.QPushButton(self.layoutWidget5)
        self.editStepButton.setObjectName("editStepButton")
        self.gridLayout_2.addWidget(self.editStepButton, 3, 0, 1, 1)
        self.deleteStepButton = QtWidgets.QPushButton(self.layoutWidget5)
        self.deleteStepButton.setObjectName("deleteStepButton")
        self.gridLayout_2.addWidget(self.deleteStepButton, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1129, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setTearOffEnabled(False)
        self.menu.setObjectName("menu")
        self.menub = QtWidgets.QMenu(self.menubar)
        self.menub.setObjectName("menub")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionResave = QtWidgets.QAction(MainWindow)
        self.actionResave.setObjectName("actionResave")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionCopyImage = QtWidgets.QAction(MainWindow)
        self.actionCopyImage.setObjectName("actionCopyImage")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menu.addAction(self.actionNew)
        self.menu.addAction(self.actionOpen)
        self.menu.addAction(self.actionSave)
        self.menu.addAction(self.actionResave)
        self.menu.addSeparator()
        self.menu.addAction(self.actionQuit)
        self.menub.addAction(self.actionCopyImage)
        self.menu_2.addAction(self.actionHelp)
        self.menu_2.addAction(self.actionAbout)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menub.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.label.setBuddy(self.keep_T)
        self.label_2.setBuddy(self.change_T)
        self.label_3.setBuddy(self.add_goods_lineEdit)
        self.label_4.setBuddy(self.blow_off_water_T)
        self.label_13.setBuddy(self.keep_T)
        self.label_14.setBuddy(self.keep_T)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.keep_T, self.keep_T_time)
        MainWindow.setTabOrder(self.keep_T_time, self.keep_T_button)
        MainWindow.setTabOrder(self.keep_T_button, self.change_T)
        MainWindow.setTabOrder(self.change_T, self.change_T_rate)
        MainWindow.setTabOrder(self.change_T_rate, self.change_T_button)
        MainWindow.setTabOrder(self.change_T_button, self.add_goods_lineEdit)
        MainWindow.setTabOrder(self.add_goods_lineEdit, self.add_goods_time)
        MainWindow.setTabOrder(self.add_goods_time, self.add_goods_button)
        MainWindow.setTabOrder(self.add_goods_button, self.blow_off_water_T)
        MainWindow.setTabOrder(self.blow_off_water_T, self.blow_off_water_rate)
        MainWindow.setTabOrder(self.blow_off_water_rate, self.blow_off_water_button)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "绘制升温曲线"))
        self.label.setText(_translate("MainWindow", "保温"))
        self.label_2.setText(_translate("MainWindow", "变温"))
        self.label_3.setText(_translate("MainWindow", "加料"))
        self.label_4.setText(_translate("MainWindow", "排水"))
        self.label_9.setText(_translate("MainWindow", "物料名称:"))
        self.label_10.setText(_translate("MainWindow", "加料时间(min):"))
        self.add_goods_button.setText(_translate("MainWindow", "添加加料步骤"))
        self.label_5.setText(_translate("MainWindow", "目标温度(℃):"))
        self.label_6.setText(_translate("MainWindow", "保温时间(min):"))
        self.keep_T_button.setText(_translate("MainWindow", "添加保温步骤"))
        self.label_7.setText(_translate("MainWindow", "目标温度(℃):"))
        self.label_8.setText(_translate("MainWindow", "变温速率(℃/min):"))
        self.change_T_button.setText(_translate("MainWindow", "添加变温步骤"))
        self.label_11.setText(_translate("MainWindow", "排水温度(℃):"))
        self.label_12.setText(_translate("MainWindow", "变温速率(℃/min):"))
        self.blow_off_water_button.setText(_translate("MainWindow", "添加排水步骤"))
        self.label_13.setText(_translate("MainWindow", "工艺"))
        self.processUpButton.setText(_translate("MainWindow", "上移"))
        self.processDownButton.setText(_translate("MainWindow", "下移"))
        self.insertProcessButton.setText(_translate("MainWindow", "插入工艺"))
        self.deleteProcessButton.setText(_translate("MainWindow", "删除工艺"))
        self.addProcessButton.setText(_translate("MainWindow", "添加工艺"))
        self.label_14.setText(_translate("MainWindow", "步骤"))
        item = self.stepTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "项目"))
        item = self.stepTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "温度"))
        item = self.stepTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "时间"))
        item = self.stepTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "速率"))
        self.stepUpButton.setText(_translate("MainWindow", "上移"))
        self.stepDownButton.setText(_translate("MainWindow", "下移"))
        self.editStepButton.setText(_translate("MainWindow", "修改步骤"))
        self.deleteStepButton.setText(_translate("MainWindow", "删除步骤"))
        self.menu.setTitle(_translate("MainWindow", "文件(&F)"))
        self.menub.setTitle(_translate("MainWindow", "编辑(&E)"))
        self.menu_2.setTitle(_translate("MainWindow", "关于"))
        self.actionNew.setText(_translate("MainWindow", "新建"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "打开"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "保存"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionResave.setText(_translate("MainWindow", "另存为"))
        self.actionResave.setShortcut(_translate("MainWindow", "Shift+S"))
        self.actionQuit.setText(_translate("MainWindow", "退出"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionCopyImage.setText(_translate("MainWindow", "复制图像"))
        self.actionCopyImage.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionHelp.setText(_translate("MainWindow", "使用帮助"))
        self.actionHelp.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.actionAbout.setText(_translate("MainWindow", "关于软件"))
